### ISSUE TITLE
Typo in LinuxWADE.R function call

### ISSUE THREAD

**Issue by PierreLyons** [phac-nml/wade#11]
There seems to be a small typo in the LinuxWADE.R script.

The labware_GAS_amr("GAS", curr_work_dir) function call has GAS as uppercase, but in R/LabwareUpload_GAS_AMR.R, the function is defined in all lowercase. Changing the function call to all lowercase in the LinuxWADE.R fixed the issue for me locally. 

Thanks,
Pierre

**Comment by ShelleyPeterson** [comment]
Fixed
