### ISSUE TITLE
Which version of R is compatible with WADE

### ISSUE THREAD

**Issue by ahmadouboye** [phac-nml/wade#9]
hi i try several time to install wade with .
Skipping 4 packages not available: DT, Biostrings, tidyselect, tidyverse .

Can we have a process of how to install wade on linux .

**Comment by ShelleyPeterson** [comment]
Hello, 
This is not a WADE issue but an issue with installing some R packages on some Linux OS. When I tried on Fedora, DT, Biostrings and Tidyselect installed properly using the instructions given but for tidyverse the individual dependencies needed to be installed. I cannot write instructions for this as it is different for different Linux operating systems. Perhaps this article will help you. https://medium.com/@jamie84mclaughlin/installing-r-and-the-tidyverse-on-ubuntu-20-04-60170020649b
